ARG JDK_VERSION={{javaVersion}}

FROM eclipse-temurin:${JDK_VERSION}-jdk AS builder

WORKDIR /app

COPY . .

RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:${JDK_VERSION}-jdk AS runtime

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE {{port}}

ENTRYPOINT ["java", "-jar", "app.jar"]
