server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PWD}@localhost:27017/${MONGO_DB}?authSource=admin
  application:
    name: project-template-engine
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

mustache:
    template-directory: classpath:/templates/spring-boot/

slack:
    webhook-url: ${SLACK_WEBHOOK_URL}

api-keys:
  gemini:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_MODEL_URL}