server:
  port: 8080

spring:
  application:
    name: project-template-engine

mustache:
    template-directory: classpath:/templates/spring-boot/

slack:
    webhook-url: ${SLACK_WEBHOOK_URL}

api-keys:
  gemini:
    key: ${GEMINI_API_KEY}